### ISSUE TITLE
Would you provide examples of tcp stream or http?

### ISSUE THREAD

**Issue by yangc91** [aboutsip/pkts#118]
Hi，when http data is long,  I have try a lot but still can not combination tcppacket to get full  http data，would you provide examples，thanks！

**Comment by ZaNkss** [comment]
I want to do this too.But my code can not work.

**Comment by valsong** [comment]
> Hi，when http data is long, I have try a lot but still can not combination tcppacket to get full http data，would you provide examples，thanks！

`@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class HttpPacket {

    private long arrivalTime;

    private Buffer payload;

}
`



`
/**
 * HttpParser
 *
 * @author Val Song
 */
public class HttpPacketParser {

    public static final String URL_SEPARATOR = " ";

    public static List<HttpPacket> parse(File file) throws IOException {
        return parse(Pcap.openStream(file));
    }

    public static List<HttpPacket> parse(Pcap pcap) throws IOException {

        List<HttpPacket> httpPackets = new LinkedList<>();

        Map<Long, HttpPacket> halfTcpPacketMap = new HashMap<>();

        pcap.loop((packet) -> {

            if (packet.hasProtocol(Protocol.TCP) && packet.hasProtocol(Protocol.IPv4)) {

                TCPPacket tcpPacket = (TCPPacket) packet.getPacket(Protocol.TCP);

                Buffer payload = tcpPacket.getPayload();

                if (payload == null) {
                    return true;
                }

                long arrivalTime = tcpPacket.getArrivalTime();

                boolean psh = tcpPacket.isPSH();

                // FIXME ? 考虑根据 acknowledgementNumber来合并TCP包
                long acknowledgementNumber = tcpPacket.getAcknowledgementNumber();

                if (psh) {
                    HttpPacket httpPacket;
                    if ((httpPacket = halfTcpPacketMap.remove(acknowledgementNumber)) != null) {
                        httpPacket.setPayload(Buffers.wrap(httpPacket.getPayload(), payload));
                    } else {
                        httpPacket = new HttpPacket(arrivalTime, payload);
                    }
                    String[] httpContents = httpPacket.getPayload()
                            .toString()
                            .split(System.lineSeparator());
                    String firstLine = httpContents[0];
                    String[] schema = firstLine.split(URL_SEPARATOR);
                    if (schema.length != 3) {
                        // 该包有问题，需要丢弃
                        System.out.println("### illegal packet: " + httpPacket.getPayload());
                        return true;
                    }
                    httpPackets.add(httpPacket);

                } else {
                    halfTcpPacketMap.compute(acknowledgementNumber, (k, p) -> {
                        if (p == null) {
                            p = new HttpPacket(arrivalTime, payload);
                        } else {
                            p.setPayload(Buffers.wrap(p.getPayload(), payload));
                        }
                        return p;
                    });
                }

            }
            return true;
        });

        return httpPackets;
    }

}
`
Does it works? (My English is poor.)

**Comment by ZaNkss** [comment]
是要自己拼TCP包吗，我的诉求是解析出请求的方法（Get/Post之类的）、请求体、状态码等这些http的header

**Comment by valsong** [comment]
> I want to do this too.But my code can not work.

I not sure it is correct.

```java
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class HttpPacket {

    private long arrivalTime;

    private Buffer payload;

}

```


```java
public class HttpPacketParser {

    public static final String URL_SEPARATOR = " ";

    public static List<HttpPacket> parse(File file) throws IOException {
        return parse(Pcap.openStream(file));
    }

    public static List<HttpPacket> parse(Pcap pcap) throws IOException {

        List<HttpPacket> httpPackets = new LinkedList<>();

        Map<Long, HttpPacket> halfTcpPacketMap = new HashMap<>();

        pcap.loop((packet) -> {

            if (packet.hasProtocol(Protocol.TCP) && packet.hasProtocol(Protocol.IPv4)) {

                TCPPacket tcpPacket = (TCPPacket) packet.getPacket(Protocol.TCP);

                Buffer payload = tcpPacket.getPayload();

                if (payload == null) {
                    return true;
                }

                long arrivalTime = tcpPacket.getArrivalTime();

                boolean psh = tcpPacket.isPSH();

                // FIXME ? 考虑根据 acknowledgementNumber来合并TCP包
                long acknowledgementNumber = tcpPacket.getAcknowledgementNumber();

                if (psh) {
                    HttpPacket httpPacket;
                    if ((httpPacket = halfTcpPacketMap.remove(acknowledgementNumber)) != null) {
                        httpPacket.setPayload(Buffers.wrap(httpPacket.getPayload(), payload));
                    } else {
                        httpPacket = new HttpPacket(arrivalTime, payload);
                    }
                    String[] httpContents = httpPacket.getPayload()
                            .toString()
                            .split(System.lineSeparator());
                    String firstLine = httpContents[0];
                    String[] schema = firstLine.split(URL_SEPARATOR);
                    if (schema.length != 3) {
                        // 该包有问题，需要丢弃
                        System.out.println("### illegal packet: " + httpPacket.getPayload());
                        return true;
                    }
                    httpPackets.add(httpPacket);

                } else {
                    halfTcpPacketMap.compute(acknowledgementNumber, (k, p) -> {
                        if (p == null) {
                            p = new HttpPacket(arrivalTime, payload);
                        } else {
                            p.setPayload(Buffers.wrap(p.getPayload(), payload));
                        }
                        return p;
                    });
                }

            }
            return true;
        });

        return httpPackets;
    }

}

```

```java
public class PktsReadHttpPacketTest {

    public static void main(String[] args) throws IOException {


        String path = PktsReadHttpPacketTest.class.getClassLoader()
                .getResource("slb-gro-on.pcap")
                .getPath();


        BufferedWriter bw = new BufferedWriter(new FileWriter("/Users/valsong/Documents/requests.txt"));

        List<HttpPacket> httpPackets = HttpPacketParser.parse(new File(path));


        httpPackets.forEach(httpPacket -> {
            try {
                bw.write(">>>>>>>>>>");
                bw.newLine();
                bw.write(String.valueOf(httpPacket.getArrivalTime()));
                bw.newLine();
                bw.write(httpPacket.getPayload().toString());
                bw.newLine();
                bw.write("<<<<<<<<<<");
                bw.newLine();
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

        bw.flush();
        bw.close();
    }


}

```

**Comment by valsong** [comment]
> 是要自己拼TCP包吗，我的诉求是解析出请求的方法（Get/Post之类的）、请求体、状态码等这些http的header

这个打印出来是这样子的
```
POST /app/employee/save?noSign=true&foo=1 HTTP/1.1
RemoteIp: 100.100.100.100
Host: foo.com
X-Forwarded-For: 210.22.154.98
Connection: close
Content-Length: 92
uid: 847d98464fb8a802

{
  "age": 9867,
  "email": "9867",
  "height": 9867,
  "id": 9867,
  "name": "9867"
}
```
接下来不就简单了嘛

**Comment by ZaNkss** [comment]
谢谢，我的代码也可以打印出这些文本消息。不过我希望得到的是http的header与payload结构化分离，比如HttpPacket中有requstMethod和host等字段。

**Comment by valsong** [comment]
> 谢谢，我的代码也可以打印出这些文本消息。不过我希望得到的是http的header与payload结构化分离，比如HttpPacket中有requstMethod和host等字段。

这段代码是为了解决请求过长时多个tcppacket合并的问题

**Comment by valsong** [comment]
> 谢谢，我的代码也可以打印出这些文本消息。不过我希望得到的是http的header与payload结构化分离，比如HttpPacket中有requstMethod和host等字段。

刚好我这边也要做这个需求，简单写了一个，上面的代码我更新了，新增了一个将ByteBuffer转化成SimpleHttpRequest的功能，我简单测了下没啥问题

**Comment by ZaNkss** [comment]
> > 谢谢，我的代码也可以打印出这些文本消息。不过我希望得到的是http的header与payload结构化分离，比如HttpPacket中有requstMethod和host等字段。
> 
> 刚好我这边也要做这个需求，简单写了一个，上面的代码我更新了，新增了一个将ByteBuffer转化成SimpleHttpRequest的功能，我简单测了下没啥问题

对，对http的拓展需要先对tcp包进行拼接，然后把tcp的payload转换为Http协议相关的，就是定义一个http帧的概念。但是我现在对实现还没有一个好办法

**Comment by valsong** [comment]
> > > 谢谢，我的代码也可以打印出这些文本消息。不过我希望得到的是http的header与payload结构化分离，比如HttpPacket中有requstMethod和host等字段。
> > 
> > 
> > 刚好我这边也要做这个需求，简单写了一个，上面的代码我更新了，新增了一个将ByteBuffer转化成SimpleHttpRequest的功能，我简单测了下没啥问题
> 
> 对，对http的拓展需要先对tcp包进行拼接，然后把tcp的payload转换为Http协议相关的，就是定义一个http帧的概念。但是我现在对实现还没有一个好办法

你跑下我的代码看看有没有啥bug，不过要指定拦截的ip和port，我这边测了合并tcp包是没啥问题了，
然后url和header以及body等也转化成SimpleHttRequest了

**Comment by jonbo372** [comment]
Hi all,

Sorry, a year later so I hope this has been resolved already but  just some pointers just in case.

In short, your questions has nothing to do with pkts.io per se. It has to do with how to frame an HTTP message, which is slightly annoying since, unlike many binary protocols where there is a header stating how many bytes the message is, HTTP doesn't have this. SIP has similar "issues" and you would have to do something similar to what I have for my sip stack here: https://github.com/aboutsip/sipstack/blob/master/sipstack-netty-codec-sip/src/main/java/io/sipstack/netty/codec/sip/SipMessageStreamDecoder.java which is really using this https://github.com/aboutsip/sipstack/blob/master/sipstack-netty-codec-sip/src/main/java/io/sipstack/netty/codec/sip/RawMessage.java.

Anyway, I hope you managed to solve your problem a year ago!
