### ISSUE TITLE
Duplicate class com.google.polo.pairing.HexDump in pkts-buffers & pkts-core in version 3.0.9

### ISSUE THREAD

**Issue by ibevilinc** [aboutsip/pkts#133]
#132 Introduced the same class into 2 different modules which is causing the following error when used in an android build.

Duplicate class com.google.polo.pairing.HexDump found in modules jetified-pkts-buffers-3.0.9 (io.pkts:pkts-buffers:3.0.9) and jetified-pkts-core-3.0.9 (io.pkts:pkts-core:3.0.9)

**Comment by jonbo372** [comment]
ah, shit. I'm an idiot. Will fix later today...

**Comment by jonbo372** [comment]
@ibevilinc if you don't mind, please review this: https://github.com/aboutsip/pkts/pull/134
