### ISSUE TITLE
SipMessage.clone() return bad format

### ISSUE THREAD

**Issue by guooscar** [aboutsip/pkts#19]
SipMessage.clone() should be 
-------------------------------------------------------------------------------------------
INVITE sip:500@192.168.3.100 SIP/2.0
Via: SIP/2.0/UDP 192.168.3.100:9000;branch=z9hG4bK.IQzUOQipR;rport
From: <sip:600@192.168.3.100>;tag=3jx~hFRKz
To: sip:500@192.168.3.100
CSeq: 20 INVITE
Call-ID: 9e4hraVLt0
Max-Forwards: 70
Supported: outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 518
Contact: <sip:600@192.168.3.100:9000>;+sip.instance="<urn:uuid:b05bcba3-cd74-42b4-b1be-052ee0740fd2>"
User-Agent: Linphone/3.8.1 (belle-sip/1.4.0)

v=0
o=600 286 2032 IN IP4 192.168.3.100
s=Talk
c=IN IP4 192.168.3.100
t=0 0

but i got 
-------------------------------------------------------------------------------------------
INVITE sip:500@192.168.3.100 SIP/2.0
Via: SIP/2.0/UDP 192.168.3.100:9000;branch=z9hG4bK.IQzUOQipR;rport
From: <sip:600@192.168.3.100>;tag=3jx~hFRKz
To: sip:500@192.168.3.100
CSeq: 20 INVITE
Call-ID: 9e4hraVLt0
Max-Forwards: 70
Supported: outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 518
Contact: <sip:600@192.168.3.100:9000>;+sip.instance="<urn:uuid:b05bcba3-cd74-42b4-b1be-052ee0740fd2>"
User-Agent: Linphone/3.8.1 (belle-sip/1.4.0)
v=0
o=600 286 2032 IN IP4 192.168.3.100
s=Talk
c=IN IP4 192.168.3.100
t=0 0

it should have an empty line below User-Agent

**Comment by jonbo372** [comment]
Yep, def not correct. Will fix asap.

**Comment by jonbo372** [comment]
I am unable to reproduce the issue. Would it be possible to share the code that you have? There are unit tests for cloning and they are fine. I also tried to actually access the various headers and then cloning but still unable to reproduce.

**Comment by guooscar** [comment]
forget it, may be it's sipstack 's bug,i use sipstack to build a sip container,now it's almost done
