### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by isbecker** [aboutsip/pkts#26]
This would be a really big issue for anyone wanting to use this in production as IPv6 is becoming more widespread.

**Comment by aboutsip** [comment]
Agreed. Currently though, I have no need for it myself since all work I do is deployed on AWS VPC and they currently do not support IPv6 but as you note, at some point it will be crucial to add support for this. Until then, please feel free to add support.

**Comment by epall** [comment]
I may be tackling this shortly
