### ISSUE TITLE
There is a SipParseException class duplication

### ISSUE THREAD

**Issue by jaimecasero** [aboutsip/pkts#27]
apparently there is a duplication coming form different modules:
-pkts-core
-pkts-sip

I guess the one in core should survive

**Comment by aboutsip** [comment]
Thanks Jaime, will fix that. My experimental 2.0 branch is complete so I'm going to fix it there and then merge it all after I have fixed all the documentation as well.

**Comment by aboutsip** [comment]
Hmmm... unfortunately they are not the same. Stupid of me to name them the same thing and under the same package too. They inherit from different base exceptions and also have slightly different intent. I guess one of them has to be renamed/moved.
