### ISSUE TITLE
MACAddress mix up in MacPacket

### ISSUE THREAD

**Issue by thaeger71** [aboutsip/pkts#44]
Hi there,

found another issue, the MAC address is mixed up. The source is destination and vice versa.
It's just a mix up in the order, the second mac is source and the first is destination. The change has to be done in MACPacket in functions getSourceMacAddress, getDestinationMacAddress and setMacAddress.

Source is 6 bytes from 6th
Destination is 6 bytes from 1st

**Comment by aboutsip** [comment]
Thanks! Fixed in: https://github.com/aboutsip/pkts/pull/46
