### ISSUE TITLE
is pkts support gprs [gb,gi,gn] protocol well?

### ISSUE THREAD

**Issue by LaiHuanMin** [aboutsip/pkts#90]
hello,i'm deving a project about write pcap file by origin mysql table data, it's maybe need create a frame, and set frameNumber, srcIp,destIp,srcPort,destPort and so on into the object.   After setting data, output those info into a pcap file.       
I wonder if the pkts support gb,gi,gn protocol and write info into pcap file, thanks a lot!

**Comment by aboutsip** [comment]
Hi,

Thanks for taking an interest in pkts.io and the answer to your question is yes and no :-) GPRS being primarily an IP based protocol (even though you can also run it across x.25 but I assume you are not) and pkts.io has implemented full support for IPv4 and experimental support for IPv6 (GRX networks are IPv4 right now as far as I know) and as such, it supports any IP based protocol. Also, GTP-U/C are using UDP, which pkts.io also supports so you have all the support you need up until layer 4. However, GTP is an application layer protocol and currently pkts.io has not implemented that. I actually do have a need myself to add it so I may implement it in the next 6 months or so but I can't give any guarantees. Of course, feel free to start adding GTP, pull requests are always welcome!

/Jonas

**Comment by LaiHuanMin** [comment]
@aboutsip thanks for what you done for pkts.io, great job!
