### ISSUE TITLE
Where's the javadoc for pkts.io?

### ISSUE THREAD

**Issue by LaiHuanMin** [aboutsip/pkts#91]
Hi, I wanna found a javadoc website to dev, and the URL http://www.aboutsip.com/pktsio/www.javadoc.io has losed(404 Not Found). Is the URL has update?

**Comment by aboutsip** [comment]
Ok, I'll fix that but you can check them out at http://www.javadoc.io/doc/io.pkts/pkts-core/3.0.3 and use the drop-down menu to see the other packages in the pkts.io family.
